# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(364, 102)
        MainWindow.setWindowOpacity(0.7)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 362, 79))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.mainLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.mainLayout.setHorizontalSpacing(10)
        self.mainLayout.setVerticalSpacing(15)
        self.mainLayout.setObjectName("mainLayout")
        self.task_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.task_combo.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_combo.setFont(font)
        self.task_combo.setObjectName("task_combo")
        self.mainLayout.addWidget(self.task_combo, 0, 1, 1, 2, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.runningForText = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runningForText.setFont(font)
        self.runningForText.setIndent(5)
        self.runningForText.setObjectName("runningForText")
        self.horizontalLayout_2.addWidget(self.runningForText, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.timeFromStart_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeFromStart_lb.setFont(font)
        self.timeFromStart_lb.setIndent(5)
        self.timeFromStart_lb.setObjectName("timeFromStart_lb")
        self.horizontalLayout_2.addWidget(self.timeFromStart_lb, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tp_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.tp_combo.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tp_combo.setFont(font)
        self.tp_combo.setObjectName("tp_combo")
        self.horizontalLayout.addWidget(self.tp_combo, 0, QtCore.Qt.AlignVCenter)
        self.totalForPeriod_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalForPeriod_lb.setFont(font)
        self.totalForPeriod_lb.setIndent(10)
        self.totalForPeriod_lb.setObjectName("totalForPeriod_lb")
        self.horizontalLayout.addWidget(self.totalForPeriod_lb, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainLayout.addLayout(self.horizontalLayout, 1, 1, 1, 2)
        self.startStop_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.startStop_btn.setMinimumSize(QtCore.QSize(120, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.startStop_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startStop_btn.setFont(font)
        self.startStop_btn.setObjectName("startStop_btn")
        self.mainLayout.addWidget(self.startStop_btn, 0, 3, 1, 1, QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 21))
        self.menubar.setObjectName("menubar")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        self.menuTasks = QtWidgets.QMenu(self.menubar)
        self.menuTasks.setObjectName("menuTasks")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionDay = QtWidgets.QAction(MainWindow)
        self.actionDay.setObjectName("actionDay")
        self.actionWeek = QtWidgets.QAction(MainWindow)
        self.actionWeek.setObjectName("actionWeek")
        self.actionMonth = QtWidgets.QAction(MainWindow)
        self.actionMonth.setObjectName("actionMonth")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionTask = QtWidgets.QAction(MainWindow)
        self.actionTask.setObjectName("actionTask")
        self.actionLog_Time = QtWidgets.QAction(MainWindow)
        self.actionLog_Time.setObjectName("actionLog_Time")
        self.actionAdd_Memo = QtWidgets.QAction(MainWindow)
        self.actionAdd_Memo.setObjectName("actionAdd_Memo")
        self.menuReport.addAction(self.actionDay)
        self.menuReport.addAction(self.actionWeek)
        self.menuReport.addAction(self.actionMonth)
        self.menuReport.addSeparator()
        self.menuReport.addAction(self.actionTask)
        self.menuTasks.addAction(self.actionAdd)
        self.menuTasks.addAction(self.actionDelete)
        self.menuTasks.addAction(self.actionModify)
        self.menuTasks.addSeparator()
        self.menuTasks.addAction(self.actionLog_Time)
        self.menuTasks.addAction(self.actionAdd_Memo)
        self.menubar.addAction(self.menuTasks.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Tracker"))
        self.runningForText.setText(_translate("MainWindow", "Now:"))
        self.timeFromStart_lb.setText(_translate("MainWindow", "0m"))
        self.totalForPeriod_lb.setText(_translate("MainWindow", "0m"))
        self.startStop_btn.setText(_translate("MainWindow", "Start"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.menuTasks.setTitle(_translate("MainWindow", "Tasks"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionDay.setText(_translate("MainWindow", "Day"))
        self.actionWeek.setText(_translate("MainWindow", "Week"))
        self.actionMonth.setText(_translate("MainWindow", "Month"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionModify.setText(_translate("MainWindow", "Modify"))
        self.actionTask.setText(_translate("MainWindow", "Task"))
        self.actionLog_Time.setText(_translate("MainWindow", "Log Time"))
        self.actionAdd_Memo.setText(_translate("MainWindow", "Add Memo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

