# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(364, 102)
        MainWindow.setWindowOpacity(0.7)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 362, 79))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.mainLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.mainLayout.setHorizontalSpacing(10)
        self.mainLayout.setVerticalSpacing(15)
        self.mainLayout.setObjectName(_fromUtf8("mainLayout"))
        self.task_combo = QtGui.QComboBox(self.gridLayoutWidget)
        self.task_combo.setMinimumSize(QtCore.QSize(230, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_combo.setFont(font)
        self.task_combo.setObjectName(_fromUtf8("task_combo"))
        self.mainLayout.addWidget(self.task_combo, 0, 1, 1, 2, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.runningForText = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.runningForText.setFont(font)
        self.runningForText.setIndent(5)
        self.runningForText.setObjectName(_fromUtf8("runningForText"))
        self.horizontalLayout_2.addWidget(self.runningForText, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.timeFromStart_lb = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeFromStart_lb.setFont(font)
        self.timeFromStart_lb.setIndent(5)
        self.timeFromStart_lb.setObjectName(_fromUtf8("timeFromStart_lb"))
        self.horizontalLayout_2.addWidget(self.timeFromStart_lb, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainLayout.addLayout(self.horizontalLayout_2, 1, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tp_combo = QtGui.QComboBox(self.gridLayoutWidget)
        self.tp_combo.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tp_combo.setFont(font)
        self.tp_combo.setObjectName(_fromUtf8("tp_combo"))
        self.horizontalLayout.addWidget(self.tp_combo, QtCore.Qt.AlignVCenter)
        self.totalForPeriod_lb = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalForPeriod_lb.setFont(font)
        self.totalForPeriod_lb.setIndent(10)
        self.totalForPeriod_lb.setObjectName(_fromUtf8("totalForPeriod_lb"))
        self.horizontalLayout.addWidget(self.totalForPeriod_lb, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mainLayout.addLayout(self.horizontalLayout, 1, 1, 1, 2)
        self.startStop_btn = QtGui.QPushButton(self.gridLayoutWidget)
        self.startStop_btn.setMinimumSize(QtCore.QSize(120, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.startStop_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startStop_btn.setFont(font)
        self.startStop_btn.setObjectName(_fromUtf8("startStop_btn"))
        self.mainLayout.addWidget(self.startStop_btn, 0, 3, 1, 1, QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 364, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuReport = QtGui.QMenu(self.menubar)
        self.menuReport.setObjectName(_fromUtf8("menuReport"))
        self.menuTasks = QtGui.QMenu(self.menubar)
        self.menuTasks.setObjectName(_fromUtf8("menuTasks"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.actionDay = QtGui.QAction(MainWindow)
        self.actionDay.setObjectName(_fromUtf8("actionDay"))
        self.actionWeek = QtGui.QAction(MainWindow)
        self.actionWeek.setObjectName(_fromUtf8("actionWeek"))
        self.actionMonth = QtGui.QAction(MainWindow)
        self.actionMonth.setObjectName(_fromUtf8("actionMonth"))
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionModify = QtGui.QAction(MainWindow)
        self.actionModify.setObjectName(_fromUtf8("actionModify"))
        self.actionTask = QtGui.QAction(MainWindow)
        self.actionTask.setObjectName(_fromUtf8("actionTask"))
        self.menuReport.addAction(self.actionDay)
        self.menuReport.addAction(self.actionWeek)
        self.menuReport.addAction(self.actionMonth)
        self.menuReport.addSeparator()
        self.menuReport.addAction(self.actionTask)
        self.menuTasks.addAction(self.actionAdd)
        self.menuTasks.addAction(self.actionDelete)
        self.menuTasks.addAction(self.actionModify)
        self.menubar.addAction(self.menuTasks.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Tracker", None))
        self.runningForText.setText(_translate("MainWindow", "Now:", None))
        self.timeFromStart_lb.setText(_translate("MainWindow", "0m", None))
        self.totalForPeriod_lb.setText(_translate("MainWindow", "0m", None))
        self.startStop_btn.setText(_translate("MainWindow", "Start", None))
        self.menuReport.setTitle(_translate("MainWindow", "Report", None))
        self.menuTasks.setTitle(_translate("MainWindow", "Tasks", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.actionDay.setText(_translate("MainWindow", "Day", None))
        self.actionWeek.setText(_translate("MainWindow", "Week", None))
        self.actionMonth.setText(_translate("MainWindow", "Month", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionModify.setText(_translate("MainWindow", "Modify", None))
        self.actionTask.setText(_translate("MainWindow", "Task", None))

